apiVersion: v1
kind: ConfigMap
metadata:
  name: schedule.cfg
data:
  config.yml: |
    address: ":6000"
    tls: <TLS配置，非必须>
      cert:
      key:
    node: <节点标识>
    database:
      uri: mongodb://<username>:<password>@<host>:<port>/<database>?authSource=<authSource>
      name: <数据库名>
      collection: <默认集合>
    transfer:
      address: "transfer-svc:6000"
      topic: schedule
      tls:
        cert: