address: ":6000"
tls: <TLS配置，非必须>
  cert:
  key:
node: <节点ID>
database:
  uri: mongodb://<username>:<password>@<host>:<port>/<database>?authSource=<authSource>
  name: <数据库名>
  collection: <默认集合>
transfer:
  address: "transfer:6000"
  tls:
    cert: