apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schedule
  name: schedule-deploy
spec:
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - image: ccr.ccs.tencentyun.com/weplanx/schedule:latest
          imagePullPolicy: Always
          name: schedule
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: config
              mountPath: "/app/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: schedule.cfg
            items:
              - key: "config.yml"
                path: "config.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-svc
spec:
  ports:
    - port: 6000
      protocol: TCP
  selector:
    app: schedule